### ISSUE TITLE
Npath

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent-echarts#17]
Place holder for work that needs to be done to support Npath

**Comment by JoshSchoen** [comment]
@jeremysmartt I don't think I can move this to in progress but I am starting to work in it.

**Comment by jeremysmartt** [comment]
@JoshSchoen Try moving it to in progress now, does it work for you?

**Comment by JoshSchoen** [comment]
That did it, thanks!

**Comment by jeremysmartt** [comment]
👍

**Comment by jeremysmartt** [comment]
@JoshSchoen Can you write up a design doc on how you are thinking this is going to work and the API and such for it here:
https://github.com/Teradata/covalent/wiki/Design-doc-directory

**Comment by JoshSchoen** [comment]
@jeremysmartt are you referring to this issue https://github.com/Teradata/covalent-echarts/issues/21 or something else?

**Comment by jeremysmartt** [comment]
nope, referring to Npath

**Comment by JoshSchoen** [comment]
Gotcha - no problem, need to get my head around it as well so this will be a good exercise anyway.

**Comment by jeremysmartt** [comment]
👍
