### ISSUE TITLE
Base Echarts Component

### ISSUE THREAD

**Issue by jeremysmartt** [Teradata/covalent-echarts#2]
Please post your prioritized chart type feature requests here as we kick off the echarts effort
https://ecomfe.github.io/echarts-examples/public/index.html

**Comment by jeremysmartt** [comment]
From internal:
I'd like to see sankey charts and sigma charts to start.  Pretty much anything that was available in the old Aster AppCenter

**Comment by richavyas** [comment]
[Research Doc](https://docs.google.com/document/d/1MPsvmy_Uw8_LVw7nbnNNE01suWkxWCjoeL6PiQ2iWxI/edit?usp=sharing)

**Comment by JoshSchoen** [comment]
Hey All, not sure if you want to have this discussion here but I've been poking my nose into echarts at a high-level and I have a few observations which you probably already know but thought it was worth add it here. I also understand the project is in it's very early stages so wanted to start of these conversations now. I'll keep digging and jump in to contribute as much as I can.

- I think there needs to be a way for developers to clearly understand what the API is for each available chart type. Obviously there is a a lot of possibilities and custom options but this could come in a form of interface definitions either for chart type or different property configurations on the options which could represent similar chart type structures. For example, a tree chart may be the same as a Sankey (or not). The point is spending some time to group these might help with documenting for a better developer experience and create a nice pattern for wrapping these charts in angular.

- Has there been any consideration on breaking up common elements of a typical chart into smaller components? For example legends, I'm sure all of us can agree that a fixed legend in terms of layout can be difficult to work around with complicated views and responsive design best practices particularly if there's a lot of series and data points.

- In the `TdChartComponent` there are 17 inputs, I wonder if there is a way to simplify this by combining things like xAxis/yAxis and again perhaps breaking into it's own component.

- ngDoCheck fires a lot, checking if the width has changed along with adding a a setInterval or debounceTime should help with this.

I don't want to create more noise for you all so if you are in the middle of these conversations great, if not feel free to reach out, happy to contribute and very exited to see where this project goes.
