### ISSUE TITLE
Bar Charts

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent-echarts#3]
## Feature Request
https://ecomfe.github.io/echarts-examples/public/index.html#chart-type-bar

Think we need to initially have the following:
- horizontal https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-y-category
- vertical https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-tick-align
- Stack bar - horizontal and vertical. https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-y-category-stack
- series support https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-label-rotation
- histogram support

### Other Considerations
- Configurable legend placement
- Color inputs options
- interfaces to describe the configuration options for good dev UX.
- custom tooltips and legend formatting
- label fonts and theming

**Comment by kyleledbetter** [comment]
![bartchart](https://user-images.githubusercontent.com/867883/44370130-bba07800-a48d-11e8-8cfc-3d16552dcdb0.jpg)
is this what you're envisioning? :P

**Comment by JoshSchoen** [comment]
LOL - caught me typing fast, it's more like this.
![download](https://user-images.githubusercontent.com/8234649/44370495-0fb45800-a4a0-11e8-83b0-775bcc525795.jpeg)
