### ISSUE TITLE
refactor: use takeUntil(destroy$) instead of storing Subscription instances

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent-echarts#30]
#### Feature Request

Use the `takeUntil` pattern instead of manually invoking `unsubscribe`.

#### Current behavior

For example in [the base component](https://github.com/Teradata/covalent-echarts/blob/develop/src/platform/echarts/base/chart.component.ts#L32), a lot of nested calls result of nested calls are required in order to store all subscriptions, which IMO reduces readability.

#### What is the motivation / use case for changing the behavior?

IMO is cleaner. See [the explanation for it
](https://alligator.io/angular/takeuntil-rxjs-unsubscribe/)

**Comment by emoralesb05** [comment]
Trying this in the last commit, seems to be working without issues.
