### ISSUE TITLE
[Feature]: Create custom themes

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent-echarts#34]
#### Feature Request

We need to create Material / Covalent / Teradata themes that get imported by default when needed.

Links for info:

http://echarts.baidu.com/theme-builder/

https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Overview%20of%20Style%20Customization

**Comment by natashasandiego** [comment]
[eChart.Themes.zip](https://github.com/Teradata/covalent-echarts/files/2659001/eChart.Themes.zip)
