### ISSUE TITLE
Chart re-renders upon config Input changes

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent-echarts#39]
#### Bug Report
Chart re-renders upon config Input changes TdChartComponent
Possibly caused by https://github.com/Teradata/covalent-echarts/blob/58c331958cd65fe9b3fdb9f40926bb914d28d05b/src/platform/echarts/base/chart.component.ts#L119 
StackBlitz example of issue: https://stackblitz.com/edit/covalent-echarts-config-update

#### What is the expected behavior?
Chart updates without re-rendering

#### What is the motivation / use case for changing the behavior?
Provides a better UX as the chart should update more gracefully

**Comment by JoshSchoen** [comment]
@emoralesb05 removing `this._instance.clear();` seems  to do the trick. I have tested it on the bar config example shown below. I'll  do some more testing on the other chart types but I don't see what  it would act any different.
![config-clear](https://user-images.githubusercontent.com/8234649/48948178-406db880-eef9-11e8-9bb5-ffc5d5ffc93d.gif)

Do you think we need to expose .clear() as a public method in case it needs to be called  externally from the `TdChartComponent`?

**Comment by emoralesb05** [comment]
i think we can remove it if it doesnt cause any issues and expose the `instance` of echarts.. that way people can hook into anything from echarts without us having to explicitly expose every single thing from it.
