### ISSUE TITLE
Click event not providing data on what was clicked in a line graph

### ISSUE THREAD

**Issue by sammeidinger** [Teradata/covalent-echarts#43]
*bug*

#### Bug Report
Stackblitz: https://stackblitz.com/edit/angular-gk1tvv?file=src%2Fapp%2Fapp.component.ts

When a data point is clicked, I would expect the event passed to a function in my component would contain information on what was clicked and the data point's value.  Maybe the series info as well. Below is the event returned to the onClick function.  I don't see such information.  NGX charts did provide such information.  This is observed in 2.0.0-beta.2.  Angular 7.0.4.  Firefox Quantum x64 63.0.3. Windows 10.

click
​altKey: false
​bubbles: true
​button: 0
​buttons: 0
​cancelBubble: false
​cancelable: true
​clientX: 293
​clientY: 385
​composed: true
​ctrlKey: false
​currentTarget: null
​defaultPrevented: false
​detail: 1
​eventPhase: 0
​explicitOriginalTarget: <canvas style="position: absolute; left: 0px; top: 0px; width: 539px; height: 600px; -moz-user-select: none; padding: 0px; margin: 0px; border-width: 0px;" data-zr-dom-id="zr_0" width="539" height="600">
​isTrusted: true
​layerX: 285
​layerY: 377
​metaKey: false
​movementX: 0
​movementY: 0
​mozInputSource: 1
mozPressure: 0
offsetX: 0
offsetY: 0
originalTarget: <canvas style="position: absolute; left: 0px; top: 0px; width: 539px; height: 600px; -moz-user-select: none; padding: 0px; margin: 0px; border-width: 0px;" data-zr-dom-id="zr_0" width="539" height="600">
pageX: 293
pageY: 385
rangeOffset: 0
rangeParent: null
region: ""
relatedTarget: null
returnValue: true
screenX: 1604
screenY: 622
shiftKey: false
srcElement: <canvas style="position: absolute; left: 0px; top: 0px; width: 539px; height: 600px; -moz-user-select: none; padding: 0px; margin: 0px; border-width: 0px;" data-zr-dom-id="zr_0" width="539" height="600">
target: <canvas style="position: absolute; left: 0px; top: 0px; width: 539px; height: 600px; -moz-user-select: none; padding: 0px; margin: 0px; border-width: 0px;" data-zr-dom-id="zr_0" width="539" height="600">
timeStamp: 81130
type: "click"
view: Window https://angular-gk1tvv.stackblitz.io/
which: 1
x: 293
y: 385
zrDelta: -0.3333333333333333
zrX: 285
zrY: 377
<prototype>: MouseEventPrototype { initMouseEvent: initMouseEvent(), getModifierState: getModifierState(), initNSMouseEvent: initNSMouseEvent(), … }

**Comment by emoralesb05** [comment]
This will be taken care of in `rc.1`.. we still need to add documentation about the events but `(click)` is actually taken by the native events.. so we have to use events like `(chartClick)` , `(chartDblclick)` and `(chartContextmenu)`.

Leaving this issue open in the meantime to add documentation about the events in the chart.
