### ISSUE TITLE
Combination Bar/Line - Area Chart

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent-echarts#5]
## Feature Request
https://ecomfe.github.io/echarts-examples/public/editor.html?c=mix-line-bar

Think we need to initially have the following:
- Series support for both line and bar
- Area support instead of lines
- Reference lines, ie. -  min, max, mean but should be configurable

### Other Considerations
- Configurable legend placement
- Color inputs options
- interfaces to describe the configuration options for good dev UX.
- custom tooltips and legend formatting
- label fonts and theming
- Event emitters to facilitate cross filtering
- annotations

**Comment by jeremysmartt** [comment]
This is done
