### ISSUE TITLE
Graph Chart (formerly pack bubbles)

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent-echarts#6]
## Feature Request
Example from, Tableau: <img width="912" alt="screen shot 2018-08-20 at 5 19 49 pm" src="https://user-images.githubusercontent.com/8234649/44369811-53599280-a49d-11e8-9e34-7828ac87bd77.png">

### Considerations
- Configurable legend placement
- Color inputs options
- interfaces to describe the configuration options for good dev UX.
- custom tooltips and legend formatting
- label fonts and theming
- Event emitters to facilitate cross filtering
- annotations

**Comment by jeremysmartt** [comment]
@JoshSchoen Feel free to modify this issue rather than open a new one.

**Comment by emoralesb05** [comment]
Taken care of with https://github.com/Teradata/covalent-echarts/pull/35
